; Script generated by the Inno Setup Script Wizard.
; Corrigido para APP 32-bits em Windows 64-bits (WOW64)
; DLLs ficam junto do EXE

#define MyAppName "MNote2"
#define MyAppVersion "2.54"
#define MyAppPublisher "Maurinsoft"
#define MyAppURL "http://maurinsoft.com.br"
#define MyAppExeName "MNote2.exe"

[Setup]
PrivilegesRequired=admin

AppId={{5D8E2FD0-2823-4697-B0CE-7623F3C4ECF6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

; ===== 32-bits =====
;ArchitecturesAllowed=x86
;ArchitecturesInstallIn64BitMode=x86
DefaultDirName={pf32}\MEDIT2

DisableProgramGroupPage=yes

OutputDir=D:\projetos\maurinsoft\MNote2\bin
OutputBaseFilename=win_MNote2_54
SetupIconFile=D:\projetos\maurinsoft\MNote2\src\MNote2.ico

Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; ===== EXE (32-bit) =====
Source: "D:\projetos\maurinsoft\MNote2\src\MNote2.exe"; DestDir: "{app}"; Flags: ignoreversion

; ===== Arquivos auxiliares =====
Source: "D:\projetos\maurinsoft\MNote2\src\*.dci"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\MNote2\src\*.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\MNote2\src\*.bat"; DestDir: "{app}"; Flags: ignoreversion

; ===== DLLs do projeto (devem ser 32-bit) - ficam junto do EXE =====
Source: "D:\projetos\maurinsoft\MNote2\src\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; ===== Tools =====
Source: "D:\projetos\maurinsoft\MNote2\tools\windows\srvFalar_1.4.exe"; DestDir: "{app}\tools"; Flags: ignoreversion

; ===== Samples =====
Source: "D:\projetos\maurinsoft\MNote2\sample\gcc\hello.c"; DestDir: "{app}\sample\gcc"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\MNote2\sample\python\hello\hello.py"; DestDir: "{app}\sample\python\hello"; Flags: ignoreversion

; ===== LIBS: COPIAR SOMENTE WIN32 JUNTO DO EXE =====
; SQLite (32-bit)
;Source: "D:\projetos\maurinsoft\MNote2\libs\sqlite\win32\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; PostgreSQL (32-bit) - normalmente libpq.dll + dependências
;Source: "D:\projetos\maurinsoft\MNote2\src\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; MySQL (32-bit) - libmysql.dll / libmysqlclient.dll 32-bit
Source: "D:\projetos\maurinsoft\MNote2\src\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; ===== NÃO COPIAR WIN64 JUNTO DO EXE (comentado pra não quebrar) =====
;Source: "D:\projetos\maurinsoft\MNote2\libs\sqlite\win64\*.dll"; DestDir: "{app}\_win64\sqlite"; Flags: ignoreversion
;Source: "D:\projetos\maurinsoft\MNote2\libs\postgres\win64\*.dll"; DestDir: "{app}\_win64\postgres"; Flags: ignoreversion
;Source: "D:\projetos\maurinsoft\MNote2\libs\mysql\win64\*.dll"; DestDir: "{app}\_win64\mysql"; Flags: ignoreversion

; ===== ESTA LINHA ERA 64-bit (NÃO PODE JUNTO DO EXE 32-bit) =====
;Source: "D:\projetos\maurinsoft\MNote2\src\libs\win64\libmysql64.dll"; DestDir: "{app}"; Flags: ignoreversion

; ===== Copia DB para C:\db (requer admin) =====
Source: "D:\projetos\maurinsoft\MNote2\db\*.*"; DestDir: "C:\db"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\tools\srvFalar_1.4.exe"; Description: "Iniciar srvFalar"; Flags: nowait postinstall skipifsilent runascurrentuser
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser